CREATE TABLE IF NOT EXISTS B2B (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(50),
    booking_id VARCHAR(50),
    hsn_sac_code VARCHAR(50),
    service_description TEXT,
    customer_name VARCHAR(100),
    date DATE,
    place_of_supply VARCHAR(100),
    type_or_category VARCHAR(100),
    txn_details TEXT,
    tax_payable_under_rcm VARCHAR(10),
    cin VARCHAR(50),
    business_name VARCHAR(150),
    business_address TEXT,
    business_gstin VARCHAR(50),
    from_location VARCHAR(100),
    to_location VARCHAR(100),
    flight_date DATE,
    flight_number VARCHAR(50),
    passenger_name VARCHAR(100),
    e_ticket VARCHAR(100),
    pnr VARCHAR(50),
    fare_charges DECIMAL(10,2),
    service_fee DECIMAL(10,2),
    effective_discount DECIMAL(10,2),
    igst DECIMAL(10,2)
);
